/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pfefinal;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;
import static pfefinal.PFEfinal.*;
import pfefinal.inter;
/**
 *
 * @author Administrator
 */
public class electre extends javax.swing.JFrame {

    /**
     * Creates new form electre
     */
    public electre() {
        initComponents();
        // setEnabled(false);
        pan1.setLayout(new BoxLayout(pan1,BoxLayout.Y_AXIS));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        pan1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jPanel2 = new javax.swing.JPanel();
        tsc = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tb = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        mat1 = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txt1 = new javax.swing.JLabel();
        txt2 = new javax.swing.JLabel();

        jMenuItem1.setText("jMenuItem1");

        jMenu1.setText("jMenu1");

        jMenu2.setText("jMenu2");

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenu5.setText("jMenu5");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Electre");
        setIconImages(null);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        jScrollPane4.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Matrice de Concordance :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane4.setViewportView(tab);

        pan1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Indices de Discordance :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        javax.swing.GroupLayout pan1Layout = new javax.swing.GroupLayout(pan1);
        pan1.setLayout(pan1Layout);
        pan1Layout.setHorizontalGroup(
            pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 345, Short.MAX_VALUE)
        );
        pan1Layout.setVerticalGroup(
            pan1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 364, Short.MAX_VALUE)
        );

        jScrollPane3.setViewportView(pan1);

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Veillez Ajoutez les Seuils :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        tsc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tscActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Seuil de Concordance :");

        tb.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Critère", "Poids", "seuil de discordance"
            }
        ));
        jScrollPane1.setViewportView(tb);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("Tester");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton2.setText("Annuler");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(56, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(tsc, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(122, 122, 122))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tsc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(67, 67, 67)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(124, Short.MAX_VALUE))
        );

        jScrollPane5.setViewportView(jPanel2);

        jScrollPane6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder(null, "Matrice d'Evaluation :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12)))); // NOI18N

        mat1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(mat1);

        jScrollPane6.setViewportView(jScrollPane2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createMatteBorder(2, 2, 2, 2, new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nombre de Critères :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel3.setText("Nombre d'Actions :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txt2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txt1, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 20, Short.MAX_VALUE)
                    .addComponent(txt2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 395, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(115, 115, 115))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(58, 58, 58))))
            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tscActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tscActionPerformed
         // TODO add your handling code here:
    }//GEN-LAST:event_tscActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      //inter in=new inter();
    //String test[][]=new String[a][a];
      //inter e=new inter();
    try{ 
        int a=Integer.parseInt(txt1.getText());
      int b=Integer.parseInt(txt2.getText());
      String test[][]=new String[a][a];
      double d[][]=new double[a][a];
      for(int i=0;i<a;i++){
          for(int j=0;j<a;j++){
              d[i][j]=(double) tab.getValueAt(i, j+1);
          }
      }
      //inter e=new inter();
       //int a=Integer.parseInt(e.gett1().getText());
    int m[][]=new int [a][b];
    // Object ol[]=new Object[b]; 
    int t[]=new int[b];
    //int to[]=new int[b];
   String dr[]=new String[b];
   String tf[][]=new String[a][b];
   for(int l=0;l<b;l++){
       dr[l]=(String) tb.getValueAt(l, 1);
       t[l]=Integer.parseInt(dr[l]);
       System.out.println(t[l]);
      // dr[l]=(String) tb.getValueAt(l, 2);
       //to[l]=Integer.parseInt(dr[l]);
   }
      for(int i=0;i<a;i++)
      { for(int j=1;j<=b;j++)
      {
         
         if(mat1.getValueAt(i, j)instanceof Integer) //t[j-1]=(Integer)tb.getValueAt(i, 1);
          tf[i][j-1]=String.valueOf(mat1.getValueAt(i, j));
         else tf[i][j-1]=(String) mat1.getValueAt(i, j);
         m[i][j-1]=Integer.parseInt(tf[i][j-1]);
          System.out.println(m[i][j-1]);
          
      }
      }
      // d=concordance(m,t,a);
       
      // for(int i=0;i<a;i++){
          // for(int j=0;j<a;j++)
       
               //System.out.println(d[i][j]);}
      tsc.selectAll();
      double sc=Double.parseDouble(tsc.getText());
      result_electre res=new result_electre();
   res.getlab3().setText("/");
   res.getlabel1().setText(tsc.getText());
    //{ for(int j=0;j<Integer.parseInt(mat1.getText());j++)
   //     m[i-1][j]=(int)mat1.getValueAt(i,j);
   // d=concordance(m,t,a);
   // }
   String tn[][] =new String[a][a];
    String r[]=new String[a+1];
    r[0]="Actions";
    for(int k=0;k<a;k++)
        r[k+1]=(String) mat1.getValueAt(k, 0);
    Object o[][]=new Object[a][a+1];
  for(int i=0;i<a;i++){
      for(int j=0;j<a+1;j++){
          if(j==0)
              o[i][0]=r[i+1];
          else{
              o[i][j]=d[i][j-1];
          }
      }
  }
  Object od[][]=new Object[a][a+1];
  tn=testconcordance(d,Double.parseDouble(tsc.getText()),a);
  for(int i=0;i<a;i++){
      for(int j=0;j<a+1;j++){
          if(j==0)
              od[i][0]=r[i+1];
          else{
              od[i][j]=tn[i][j-1];
          } 
          if(od[i][j]=="Non P")
             test[i][j-1]="Non P";
      }
  }
  String srt[]=new String[a+1];
  srt[0]="Actions";
  for(int i=0;i<a;i++)
      srt[i+1]=(String) mat1.getValueAt(i, 0);
  int cor[][]=new int[a][a];
 /* for(int i=0;i<b;i++){
     cor=disconcordance( m,i, a,b );
     //srt[i+1]=(String) mat1.getValueAt(i, 0);
     Object ol[][]=new Object[a+1][a+1]; 
      ol[0][0]="Actions";
     JLabel lp=new JLabel();
      
      lp.setText("Critère : "+tb.getValueAt(i, 0));
      JLabel lb1=new JLabel(" ");
      lb1.setSize(50, 10);
       JLabel lb2=new JLabel(" ");
      lb2.setSize(50, 10);
      for(int u=0;u<a+1;u++){
          
             //lp.setText("Critère"+r[].toString());
         for(int j=0;j<a+1;j++)
         {
             if(u==0 && j==0)  
               ol[u][j]="Actions";
           else if(u==0 && j!=0)
                ol[u][j]=srt[j];
                 
           else    if(j==0 && u!=0)
                 ol[u][j]=srt[u];
                
         else ol[u][j]=cor[u-1][j-1]; 
           //  if(j==0)
           //  ol[u][j]=srt[u+1];
        // else ol[u][j]=cor[u][j-1]; 
         //}
     }
      }
      JTable tr=new JTable();
      //tr.setSize(70, 60);
      tr.setModel(new DefaultTableModel(ol,srt));
      
     //JLabel lp=new JLabel();
      res.getp1().add(lb2);
      res.getp1().add(lp);
      res.getp1().add(lb1);
      res.getp1().add(tr);
  }*/
  res.gettabs().setModel(new DefaultTableModel(od,r));
   // res.gettabc().setModel(new DefaultTableModel(o,r));
    res.setVisible(true);
    for(int i=0;i<b;i++){
        JLabel lb=new JLabel();
       
      String s=(String)tb.getValueAt(i, 2);
    String dt=(String) tb.getValueAt(i, 0);
      JLabel l2=new JLabel(" ");
      l2.setSize(50, 10);
       JLabel l3=new JLabel(" ");
      l3.setSize(50, 5);
      lb.setText("Critère :"+dt +", Seuil de discordance = "+s);
      int ind=Integer.parseInt(s);
      Object disc[][]=new Object[a+1][a+1];
      JTable tp=new JTable();
      String re[][]=new String[a][a];
      re=testdiscordance(disconcordance( m,i, a,b ),ind,a);
      disc[0][0]="Action";
      for(int u=0;u<a+1;u++){
          
             //lp.setText("Critère"+r[].toString());
         
             
             for(int j=0;j<a+1;j++)
         {
            
           if(u==0 && j==0)  
               disc[u][j]="Action";
           else if(u==0 && j!=0)
                disc[u][j]=srt[j];
                 
           else    if(j==0 && u!=0)
                 disc[u][j]=srt[u];
                
         else disc[u][j]=re[u-1][j-1]; 
         
         if (disc[u][j]=="Non S")
             test[u-1][j-1]="Non P";
         }
     } 
      JTable ou=new JTable();
     ou.setModel(new DefaultTableModel(disc,srt));
      res.getpan().add(l3);
     res.getpan().add(lb);
      res.getpan().add(l2);
      res.getpan().add(ou);
     
    }
    for(int i=0;i<a;i++){
        for(int j=0;j<a;j++){
            if(test[i][j]!="Non P"){
                test[i][j]="P";
            }
            
        }
    }
    Object fin[][]=new Object[a][a+1];
    for(int i=0;i<a;i++)
        for(int j=0;j<a+1;j++){
            if(j==0)
                fin[i][j]=r[i+1];
            else fin[i][j]=test[i][j-1];
        }
    res.gettabf().setModel(new DefaultTableModel(fin,r));
   int ens[]=new int[a];
  String []noy=new String[a];
    int j=0;
  for(int i=0;i<a;i++){
        r[i+1]=(String) mat1.getValueAt(i, 0);
    ens[i]=noyau(test,i,a); 
    
    if(ens[i]==1)
       // while(j<a)
        //{
        noy[i]=r[i+1];
       
        //}
   else noy[i]="/";
  // j++;
    
   } 
  String noyo[];
  int n=0;
  for(int i=0;i<a;i++){
     if(noy[i]!="/")
         n++;
  }
  noyo=new String[n];
  int c=0;
  while(c<n){
     int k=j;
      for( k=j;k<a;k++){
       if(noy[k]!="/") 
       {  noyo[c]=noy[k];
       System.out.println(noyo[c]+"\n");
       c++;}
      }
  }
  //noyo=new String[n];
    Object noya[][]=new Object[n][1];
    for(int i=0;i<noyo.length;i++)
        noya[i][0]=noyo[i];
    String s[]=new String[]{"Actions potentiels"};
    res.gettabn().setModel(new DefaultTableModel(noya,s));
    res.getlabel2().setText(tsc.getText());
    int sum=0;
    for(int i=0;i<b;i++)
        sum+=t[i];
    res.getlabel1().setText(String.valueOf(sum));
    }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(rootPane, " Entrez un nombre svp", " ", JOptionPane.ERROR_MESSAGE);
            }
    catch(Exception ex){
        JOptionPane.showMessageDialog(rootPane, "Seuil de Concordance entre 0 et 1");
    }
    }//GEN-LAST:event_jButton1ActionPerformed
public JLabel gettxt1(){
    return txt1;
}
public JLabel gettxt2(){
    return txt2;
}
public JPanel getpan1(){
    return pan1;
}
public JTable getmat(){
    return mat1;
}
public JTable gettab(){
    return tab;
}
    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       setVisible(false); // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed
public JTable gettb(){
    return  this.tb;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(electre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(electre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(electre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(electre.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new electre().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable mat1;
    private javax.swing.JPanel pan1;
    private javax.swing.JTable tab;
    private javax.swing.JTable tb;
    private javax.swing.JTextField tsc;
    private javax.swing.JLabel txt1;
    private javax.swing.JLabel txt2;
    // End of variables declaration//GEN-END:variables
}
