/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pfefinal;

//import java.util.HashSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javafx.scene.control.CheckBox;
import javax.swing.DefaultCellEditor;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import static jdk.nashorn.tools.ShellFunctions.input;
import static pfefinal.PFEfinal.concordance;
import static pfefinal.PFEfinal.disconcordance;

/**
 *
 * @author Administrator
 */
public class inter extends javax.swing.JFrame {
private boolean maxmin;
 boolean bo1,bo2,b3,b4,b5;
    /**
     * Creates new form inter
     */
    public inter() {
        initComponents();
   // setEnabled(false);
  
       /* m.add(j);
        b1.add(m);
        b1.add(k);
        b1.setBounds(500, 500, 10, 20);
        b1.setVisible(true);
        add(b1);*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jPanel5 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        b2 = new javax.swing.JButton();
        b1 = new javax.swing.JButton();
        jScrollPane6 = new javax.swing.JScrollPane();
        jScrollPane4 = new javax.swing.JScrollPane();
        tab = new javax.swing.JTable();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        t2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ok = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tab1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tab2 = new javax.swing.JTable();
        ajouter = new javax.swing.JButton();
        jScrollPane7 = new javax.swing.JScrollPane();
        jScrollPane5 = new javax.swing.JScrollPane();
        tab3 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 279, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1432, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 957, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jMenuItem2.setText("jMenuItem2");

        jMenu3.setText("jMenu3");

        jMenu4.setText("jMenu4");

        jMenu5.setText("jMenu5");

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("Acceil");
        setBackground(new java.awt.Color(84, 200, 255));

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setAutoscrolls(true);

        jPanel4.setBackground(new java.awt.Color(204, 204, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Quitter");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(34, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
        );

        jPanel6.setBackground(new java.awt.Color(204, 204, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Choix des Methodes ?", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jButton1.setText("PROMETHEE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        b2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b2.setText("ELECTRE II");
        b2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b2ActionPerformed(evt);
            }
        });

        b1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        b1.setText("ELECTRE I");
        b1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                b1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(193, 193, 193))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(87, 87, 87))))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(b1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(b2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(127, Short.MAX_VALUE))
        );

        jScrollPane6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Matrice d'Evaluation :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N
        jScrollPane6.setPreferredSize(new java.awt.Dimension(100, 300));

        tab.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tab.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Actions/Critères"
            }
        ));
        tab.setRowSelectionAllowed(false);
        tab.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tab);

        jScrollPane6.setViewportView(jScrollPane4);

        jScrollPane1.setBorder(null);
        jScrollPane1.setPreferredSize(new java.awt.Dimension(290, 680));

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(296, 750));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("Nombre d'Actions :");

        t1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                t1ActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("Nombre de Critères :");

        ok.setBackground(new java.awt.Color(204, 204, 204));
        ok.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        ok.setText("Valider");
        ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okActionPerformed(evt);
            }
        });

        tab1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tab1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Action", "Nom"
            }
        ));
        tab1.setRowSelectionAllowed(false);
        jScrollPane2.setViewportView(tab1);

        tab2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        tab2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Critère", "Nom"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tab2.setRowSelectionAllowed(false);
        jScrollPane3.setViewportView(tab2);

        ajouter.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        ajouter.setText("Ajouter");
        ajouter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(32, 32, 32))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 141, Short.MAX_VALUE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(t1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(t1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(t2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(32, 32, 32)
                .addComponent(ok, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(54, 54, 54)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addComponent(ajouter, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(208, 208, 208))
        );

        jScrollPane1.setViewportView(jPanel1);

        jScrollPane7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cout et Poids :", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        tab3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Critère", "Poids", "Critère à Maximiser !", "Critère à Minimiser !"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Boolean.class, java.lang.Boolean.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tab3.setRowSelectionAllowed(false);
        jScrollPane5.setViewportView(tab3);
        if (tab3.getColumnModel().getColumnCount() > 0) {
            tab3.getColumnModel().getColumn(0).setPreferredWidth(20);
            tab3.getColumnModel().getColumn(1).setPreferredWidth(20);
            tab3.getColumnModel().getColumn(2).setPreferredWidth(40);
            tab3.getColumnModel().getColumn(3).setPreferredWidth(40);
        }

        jScrollPane7.setViewportView(jScrollPane5);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 561, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(105, 105, 105))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 48, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );

        jMenu1.setText("File");

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F1, 0));
        jMenuItem1.setText("New");
        jMenuItem1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu1.add(jMenuItem1);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
    inter i=new inter();
    i.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void t1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_t1ActionPerformed
       
    }//GEN-LAST:event_t1ActionPerformed
public void exp(boolean a,boolean b) throws Exception{
    if(a==b)throw new Exception();
}
    private void ajouterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterActionPerformed
   /* if(tab3.getRowCount()==0)
    {       tab3.setModel(new DefaultTableModel(new Object[][]{},new String[]{}));
            System.out.println(tab3.getRowCount());
    }
    else{ */
        DefaultTableModel mod= (DefaultTableModel)tab3.getModel();
       //tab3.setModel(new DefaultTableModel(new Object[][]{},new String[]{}));
     try 
        {
      t1.selectAll();
      t2.selectAll();
      int a=Integer.parseInt(t1.getText());
      int b=Integer.parseInt(t2.getText());
        Object ob [][]=new Object[a][b+1];
        Object obj[][]=new Object[b][3];
        String s[]=new String[b+1];
       // String se[]=new String[]{"Critère","Poids","maximiser"};
        //String s1[]=new String[a];
        s[0]="A/C";
        for(int i=0;i<b;i++){
          mod.addRow(new Object[]{tab2.getValueAt(i, 1),null,maxmin,maxmin });
         
         //obj[i][0]=tab2.getValueAt(i, 1);
            s[i+1]=(String) tab2.getValueAt(i, 1);
         //  obj[i][2]=false;*/
           
//s1[i]=(String)tab2.getValueAt(i, 1);
        }
        //Object obj[][]=new Object[a][b];
        for(int i=0;i<a;i++){
          ob[i][0]=tab1.getValueAt(i, 1);
       }
           // obj[i][0]=tab2.getValueAt(i, 1);}
        tab.setModel(new DefaultTableModel(ob,s));
      //  tab3.setModel(new DefaultTableModel(obj,se));
       // String str[]=new String[a];
     }catch(NumberFormatException e){
        JOptionPane.showMessageDialog(this, "Entrer un Nombre svp", "",JOptionPane.INFORMATION_MESSAGE );
    }
    
        //t1.setText("");
         //t2.setText("");
    }//GEN-LAST:event_ajouterActionPerformed
public JTextField gett1(){
    return t1;
}
public JTextField gett2(){
    return this.t2;
}
    public JTable gettab1(){
    return this.tab1;
}
public JTable gettab2(){
    return this.tab2;
}
public JTable gettab(){
    return this.tab;
}
public JTable gettab3(){
    return this.tab3;
}
    private void okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okActionPerformed
    
    try{ 
     t1.selectAll();
     t2.selectAll();
     String s=t1.getText();
     String s1=t2.getText();
     Integer in=Integer.parseInt(s);
     Integer im=Integer.parseInt(s1);
    //t1.setText("");
    // t2.setText("");   
    
     if((im<=0) || (in<=0))
         JOptionPane.showMessageDialog(rootPane, "Veillez entrez le nombre correctement", "", JOptionPane.ERROR_MESSAGE);
     else{
         Object ob[][]=new Object[in][2];
         String f[]=new String[]{"Action","Nom",};
         for(int i=0;i<in;i++){
           
             ob[i][0]=i+1;
            ob[i][1]=null;
            //ob[i][2]=b;
         }
         tab1.setModel(new DefaultTableModel(ob,f));
         Object o[][]=new Object[im][2];
         String fln[]=new String[]{"Critère","Nom"};
         for(int i=0;i<im;i++){
            // o[i][2]="choisir..";
           //JComboBox b=new JComboBox();
            
             //b.setModel(new DefaultComboBoxModel<String>(str));
             //b.addItem("Maximiser");
             //b.addItem("Minimiser");
            // TableColumn tab=tab2.getColumnModel().getColumn(2);
             //tab.setCellEditor(new DefaultCellEditor(b));
             o[i][0]=i+1;
            o[i][1]=null;
            
           // b.setVisible(true);
         }
         tab2.setModel(new DefaultTableModel(o,fln));
     }
     //for(int i=0;i<im;i++){
       /*  b=new JComboBox();
         String str[]=new String[]{"Maximiser","Minimiser"};
         b.setModel(new DefaultComboBoxModel<String>(str));
 
         
         TableColumn tab=tab2.getColumnModel().getColumn(2);
         tab.setCellEditor(new DefaultCellEditor(b));
         
       
           
     //}*/
    }catch(NumberFormatException e){
        JOptionPane.showMessageDialog(rootPane, "Entrer un Nombre svp", "",JOptionPane.ERROR_MESSAGE );
      
    }
    }//GEN-LAST:event_okActionPerformed


    @Override
    public void setDefaultCloseOperation(int operation) {
        super.setDefaultCloseOperation(operation); 
//To change body of generated methods, choose Tools | Templates.
    }

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
      int i=JOptionPane.showOptionDialog(rootPane, "Voulez vous Quitter ?", "",  JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);
      if(i==JOptionPane.OK_OPTION)
          System.exit(0);
    }//GEN-LAST:event_jPanel4MouseClicked

    private void b2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b2ActionPerformed
try{
        boolean bool1;
       boolean bool2;
        electre2 es=new electre2();
        es.getlab1().setText(t1.getText());
        es.getlab2().setText(t2.getText());
        int a=Integer.parseInt(t1.getText());
        int b=Integer.parseInt(t2.getText());
         String str[]=new String[b+1];
         str[0]="A/C";
        int table[][]=new int[a][b];
         String dfr[][]=new String[a][b];
       for(int i=0;i<a;i++){
           for(int j=0;j<b;j++){
               dfr[i][j]=(String) tab.getValueAt(i, j+1);
               table[i][j]=Integer.parseInt(dfr[i][j]);
           }
       }
        for(int i=1;i<=b;i++)
            
             str[i]=(String)tab2.getValueAt(i-1, 1);
         Object on[][]=new Object[a][b+1];
         for(int i=0;i<a;i++)
             on[i][0]=tab.getValueAt(i, 0);
        int input;
         for(int i=0;i<b;i++){
             bool1=(boolean) tab3.getValueAt(i, 2);
              bool2=(boolean) tab3.getValueAt(i, 3);
               exp(bool1,bool2);
            if(bool1==bool2)
            {    //   throw new deuxException();
                 input = JOptionPane.showOptionDialog(null, "veillez choisir un parmi les deux", "", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);

         
            } else   if(bool1==false && bool2==true)
                for(int j=0;j<a;j++)
               
                 
               
                     if(bool1==false && bool2==true)
                         on[j][i+1]=table[j][i]*-1;
               // on[i][j-1]=table[i][j-1]*-1;
                 // else   on[i][j]=tab.getValueAt(i, j);
          for(int k=0;k<a;k++)              
             if(on[k][i+1]==null)
              on[k][i+1]=tab.getValueAt(k,i+1 );
             
             
         }
   String s[]=new String[]{"Critère","Poids","Sueil de Discordance"};
        Object ob[][]=new Object[b][b];
       for(int i=0;i<Integer.parseInt(t2.getText());i++){
           ob[i][0]=tab2.getValueAt(i, 1);
           ob[i][1]=tab3.getValueAt(i, 1);
       }
       String st[]=new String[a+1];
       st[0]="Actions";
       for(int i=0;i<a;i++){
       st[i+1]=(String) tab.getValueAt(i, 0);
    }
       int mat[][]=new int[a][b];
       String fr[][]=new String[a][b];
       for(int i=0;i<a;i++){
           for(int j=0;j<b;j++){
           // if(tab.getValueAt(i, j+1)instanceof Integer)
           fr[i][j]=(String) tab.getValueAt(i, j+1);
           mat[i][j]=Integer.parseInt(fr[i][j]);
               //else JOptionPane.showMessageDialog(rootPane, "error", "Error", JOptionPane.ERROR_MESSAGE);
       }}
           int t[]=new int[b];
           String ft[]=new String[b];
           for(int k=0;k<b;k++)
           { ft[k]=(String) tab3.getValueAt(k, 1);
               t[k]=Integer.parseInt(ft[k]);
       
       double crd[][];
       crd=concordance(mat,t,a);
       Object obj[][]=new Object[a][a+1];
       for(int i=0;i<a;i++){
           for(int j=0;j<a+1;j++){
               if(j==0){
                   obj[i][j]=tab.getValueAt(i, 0);
               }
               else
                   obj[i][j]=crd[i][j-1];
           }
       }
       es.gettab().setModel(new DefaultTableModel(obj,st));
       es.getmat1().setModel(new DefaultTableModel(on,str));
       es.gettb().setModel(new DefaultTableModel(ob,s));
        //es.setVisible(true);
        
    } 
           /*String se[]=new String[a+1];
           Object obj[][]=new Object[a+1][a+1];
           for(int i=0;i<a;i++){
               
           }*/
           String srt[]=new String[a+1];
  srt[0]="Actions";
  for(int i=0;i<a;i++)
      srt[i+1]=(String) tab.getValueAt(i, 0);
  int cor[][]=new int[a][a];
  for(int i=0;i<b;i++){
     cor=disconcordance( mat,i, a,b );
     //srt[i+1]=(String) mat1.getValueAt(i, 0);
     Object ol[][]=new Object[a+1][a+1]; 
      ol[0][0]="Actions";
     JLabel lp=new JLabel();
      
      lp.setText("Critère : "+tab3.getValueAt(i, 0));
      JLabel lb1=new JLabel(" ");
      lb1.setSize(50, 10);
       JLabel lb2=new JLabel(" ");
      lb2.setSize(50, 10);
      for(int u=0;u<a+1;u++){
          
             //lp.setText("Critère"+r[].toString());
         for(int j=0;j<a+1;j++)
         {
             if(u==0 && j==0)  
               ol[u][j]="Actions";
           else if(u==0 && j!=0)
                ol[u][j]=srt[j];
                 
           else    if(j==0 && u!=0)
                 ol[u][j]=srt[u];
                
         else ol[u][j]=cor[u-1][j-1]; 
           //  if(j==0)
           //  ol[u][j]=srt[u+1];
        // else ol[u][j]=cor[u][j-1]; 
         //}
     }
      }
     DefaultTableModel m=new DefaultTableModel();
     m.setDataVector(ol, srt);
      JTable tr=new JTable(m);
      //tr.setSize(70, 60);
      tr.setModel(new DefaultTableModel(ol,srt));
      
     //JLabel lp=new JLabel();
      es.getpan().add(lb2);
      es.getpan().add(lp);
      es.getpan().add(lb1);
      es.getpan().add(tr);
  }
es.setVisible(true);
} catch(NumberFormatException er){
    JOptionPane.showMessageDialog(rootPane, "Type d'information entrée est erroné ou un champ vide !");
}
catch(Exception ex){
     JOptionPane.showMessageDialog(rootPane, "voulez choisir maximiser ou minimiser !");
}
    }//GEN-LAST:event_b2ActionPerformed

    private void b1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_b1ActionPerformed
        //String s[]=new String[Integer.parseInt(t1.getText())];
     //int input=0;  
            boolean bool1;
            boolean bool2;
   try{         
        electre e=new electre();
        e.gettxt1().setText(t1.getText());
         e.gettxt2().setText(t2.getText());
        int a=Integer.parseInt(t1.getText());
        int b=Integer.parseInt(t2.getText());
       int table[][]=new int[a][b];
       String dfr[][]=new String[a][b];
       for(int i=0;i<a;i++){
           for(int j=0;j<b;j++){
               dfr[i][j]=(String) tab.getValueAt(i, j+1);
               table[i][j]=Integer.parseInt(dfr[i][j]);
           }
       }
        String str[]=new String[b+1];
         str[0]="A/C";
         for(int i=1;i<=b;i++)
             str[i]=(String)tab2.getValueAt(i-1, 1);
         Object on[][]=new Object[a][b+1];
         for(int i=0;i<a;i++)
             on[i][0]=tab.getValueAt(i, 0);
         for(int i=0;i<b;i++){
             bool1=(boolean) tab3.getValueAt(i, 2);
              bool2=(boolean) tab3.getValueAt(i, 3);
            exp(bool1,bool2);
              if(bool1==bool2)
            {    //   throw new deuxException();
                int input = JOptionPane.showOptionDialog(null, "veillez choisir un parmi les deux", "", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);

         
            } else   if(bool1==false && bool2==true)
                for(int j=0;j<a;j++)
               
                 
               
                     if(bool1==false && bool2==true)
                         on[j][i+1]=table[j][i]*-1;
               // on[i][j-1]=table[i][j-1]*-1;
                 // else   on[i][j]=tab.getValueAt(i, j);
          for(int k=0;k<a;k++)              
             if(on[k][i+1]==null)
              on[k][i+1]=tab.getValueAt(k,i+1 );
             
             
         }
   String s[]=new String[]{"Critère","Poids","Sueil Discordance"};
        Object ob[][]=new Object[b][b];
       for(int i=0;i<Integer.parseInt(t2.getText());i++){
           ob[i][0]=tab2.getValueAt(i, 1);
           ob[i][1]=tab3.getValueAt(i, 1);
       }
       String st[]=new String[a+1];
       st[0]="Actions";
       for(int i=0;i<a;i++){
       st[i+1]=(String) tab.getValueAt(i, 0);
    }
       int mat[][]=new int[a][b];
       String fr[][]=new String[a][b];
       for(int i=0;i<a;i++){
           for(int j=0;j<b;j++){
           // if(tab.getValueAt(i, j+1)instanceof Integer)
           fr[i][j]=(String) tab.getValueAt(i, j+1);
           mat[i][j]=Integer.parseInt(fr[i][j]);
               //else JOptionPane.showMessageDialog(rootPane, "error", "Error", JOptionPane.ERROR_MESSAGE);
       }}
           int t[]=new int[b];
           String ft[]=new String[b];
          try{
           for(int k=0;k<b;k++)
           { ft[k]=(String) tab3.getValueAt(k, 1);
               t[k]=Integer.parseInt(ft[k]);}
         
          
       double crd[][];
       crd=concordance(mat,t,a);
       Object obj[][]=new Object[a][a+1];
       for(int i=0;i<a;i++){
           for(int j=0;j<a+1;j++){
               if(j==0){
                   obj[i][j]=tab.getValueAt(i, 0);
               }
               else
                   obj[i][j]=crd[i][j-1];
           }
       }
       e.gettab().setModel(new DefaultTableModel(obj,st));
       e.getmat().setModel(new DefaultTableModel(on,str));
       e.gettb().setModel(new DefaultTableModel(ob,s));
    
       String srt[]=new String[a+1];
  srt[0]="Actions";
  for(int i=0;i<a;i++)
      srt[i+1]=(String) tab.getValueAt(i, 0);
  int cor[][]=new int[a][a];
  for(int i=0;i<b;i++){
     cor=disconcordance( mat,i, a,b );
     //srt[i+1]=(String) mat1.getValueAt(i, 0);
     Object ol[][]=new Object[a+1][a+1]; 
      ol[0][0]="Actions";
     JLabel lp=new JLabel();
      
      lp.setText("Critère : "+tab3.getValueAt(i, 0));
      JLabel lb1=new JLabel(" ");
      lb1.setSize(50, 10);
       JLabel lb2=new JLabel(" ");
      lb2.setSize(50, 10);
      for(int u=0;u<a+1;u++){
          
             //lp.setText("Critère"+r[].toString());
         for(int j=0;j<a+1;j++)
         {
             if(u==0 && j==0)  
               ol[u][j]="Actions";
           else if(u==0 && j!=0)
                ol[u][j]=srt[j];
                 
           else    if(j==0 && u!=0)
                 ol[u][j]=srt[u];
                
         else ol[u][j]=cor[u-1][j-1]; 
           //  if(j==0)
           //  ol[u][j]=srt[u+1];
        // else ol[u][j]=cor[u][j-1]; 
         //}
     }
      }
     DefaultTableModel m=new DefaultTableModel();
     m.setDataVector(ol, srt);
      JTable tr=new JTable(m);
      //tr.setSize(70, 60);
      tr.setModel(new DefaultTableModel(ol,srt));
      
     //JLabel lp=new JLabel();
      e.getpan1().add(lb2);
      e.getpan1().add(lp);
      e.getpan1().add(lb1);
      e.getpan1().add(tr);
  }
       e.setVisible(true);
   }catch(Exception ec){
       JOptionPane.showMessageDialog(rootPane, "Veillez verifier les Informations introduites");
      
   }
           }catch(NumberFormatException ex){
              
          JOptionPane.showMessageDialog(rootPane, ex);
        //  e.setVisible(false);
  // do something
           } catch (Exception ex) {
        Logger.getLogger(inter.class.getName()).log(Level.SEVERE, null, ex);
        JOptionPane.showMessageDialog(rootPane, "Veillez choisir Maximiser ou Minimiser");
    }
    }//GEN-LAST:event_b1ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
try{
        boolean bool1;
boolean bool2;
   bo1=false;
   bo2=false;
   b3=false;
   b4=false;
   b5=false;
        int a=Integer.parseInt(t1.getText());
    int b=Integer.parseInt(t2.getText());
        Accueil ac=new Accueil(); 
        ac.getnbact().setText(t1.getText());
        ac.getnbacr().setText(t2.getText());
    Object obn[][]=new Object[a][b+1];
    String str[]=new String[b+1];
         str[0]="A/C";
        int table[][]=new int[a][b];
         String dfr[][]=new String[a][b];
       for(int i=0;i<a;i++){
           for(int j=0;j<b;j++){
               dfr[i][j]=(String) tab.getValueAt(i, j+1);
               table[i][j]=Integer.parseInt(dfr[i][j]);
           }
       }
        for(int i=1;i<=b;i++)
            
             str[i]=(String)tab2.getValueAt(i-1, 1);
         Object on[][]=new Object[a][b+1];
         for(int i=0;i<a;i++)
             on[i][0]=tab.getValueAt(i, 0);
        int input;
         for(int i=0;i<b;i++){
             bool1=(boolean) tab3.getValueAt(i, 2);
              bool2=(boolean) tab3.getValueAt(i, 3);
              exp(bool1,bool2);
            if(bool1==bool2)
            {    //   throw new deuxException();
                 input = JOptionPane.showOptionDialog(null, "veillez choisir un parmi les deux", "", JOptionPane.OK_CANCEL_OPTION, JOptionPane.INFORMATION_MESSAGE, null, null, null);

         
            } else   if(bool1==false && bool2==true)
                for(int j=0;j<a;j++)
               
                 
               
                     if(bool1==false && bool2==true)
                         on[j][i+1]=table[j][i]*-1;
               // on[i][j-1]=table[i][j-1]*-1;
                 // else   on[i][j]=tab.getValueAt(i, j);
          for(int k=0;k<a;k++)              
             if(on[k][i+1]==null)
              on[k][i+1]=tab.getValueAt(k,i+1 );
             
             
         }
    String s[]=new String[b+1];
    for(int k=0;k<b+1;k++)
    { if(k==0)
            s[k]="Actions/Critères";
        else s[k]=(String) tab2.getValueAt(k-1, 1);
    }
    DefaultTableModel mode=(DefaultTableModel)ac.getcout().getModel();
   // Object ob[][]=new Object[b][7];
    for(int i=0;i<b;i++){
        
        mode.addRow(new Object[]{tab3.getValueAt(i, 0),tab3.getValueAt(i, 1),bo1,bo2,b3,b4,b5 });
        
    }
    // JComboBox combo=new JComboBox();
           //  combo.setModel(new DefaultComboBoxModel<String>(str));
             
   // String sr[]=new String[]{"Critère","Poids","Critère usuel","Critère","Critère","Critère","Critère"};
    
           /* TableColumn tab=ac.getcout().getColumnModel().getColumn(2);
             tab.setCellEditor(new DefaultCellEditor(combo));*/
   // ac.getcout().setModel(new DefaultTableModel(ob,sr));
          
             //tab.setCellEditor(new DefaultCellEditor(combo));
    ac.getmatriceper().setModel(new DefaultTableModel(on,s));
    ac.setVisible(true);
   
{
    // do something
}
}catch(NumberFormatException ex){
    JOptionPane.showMessageDialog(rootPane, "Veillez Entrez tous les informations ou verifiez que vous utilisez des nombres");
}   catch (Exception ex) {
       // Logger.getLogger(inter.class.getName()).log(Level.SEVERE, null, ex);
       JOptionPane.showMessageDialog(rootPane, "Veillez choisir maximiser ou minimiser");
    }
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void tabMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabMouseClicked
       int index=tab.getSelectedColumn();
    }//GEN-LAST:event_tabMouseClicked
   public boolean getbo1(){
       return bo1;
   } 
    
public JButton getb()
        
{
    return this.b1;
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(inter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(inter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(inter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(inter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new inter().setVisible(true);
            }
        });

    

    }
/*JComboBox b1=new JComboBox<>();
JMenu m;
JMenuItem i,j,k;*/
    private JComboBox b;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouter;
    private javax.swing.JButton b1;
    private javax.swing.JButton b2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JButton ok;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTable tab;
    private javax.swing.JTable tab1;
    private javax.swing.JTable tab2;
    private javax.swing.JTable tab3;
    // End of variables declaration//GEN-END:variables
}
